name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.1'
          bundler-cache: true
      - name: Test
        run: bundle exec cucumber
        env:
          ALLURE_TESTPLAN_PATH: features/support/fixture
      - uses: actions/upload-artifact@v2
        with:
          name: allure-reports
          path: report/allure-results
          if-no-files-found: error
